#!/bin/sh
NAME=shadowsocksr

uci_get_by_name(){
	a=$(uci -q get $NAME.$1.$2)
	echo ${a:=$3}
}

uci_get_by_type(){
	a=$(uci -q get $NAME.@$1[0].$2)
	echo ${a:=$3}
}

test_proxy(){
	name=$(uci_get_by_name $1 server)
	ipset add ss_spec_wan_ac $name 2>/dev/null
	a=$?
	b=$(tcping -c $time_b -i 1 -t 2 -p $(uci_get_by_name $1 server_port) $name 2>/dev/null | grep 'failed' | awk -F ',' '{print$3}' | awk -F . '{print$1}')
	[ $a = 0 ] && ipset del ss_spec_wan_ac $name 2>/dev/null
	[ -z "$b" -o "$b" -gt 50 ] && return 1 || return 0
}

check_proxy(){
	for i in $(seq 1 $(uci_get_by_type global switch_try_count 3));do
		curl -so /dev/null -m $time_b www.google.com && return 0
		curl -so /dev/null -m $time_b www.baidu.com && a=1 || a=2
		sleep 1
	done
	return $a
}

select_proxy(){
	SERVER_C=0
	a=$(uci -X show $NAME | grep =servers)
	b=$(echo "$a" | wc -l)
	[ $c -ge $b ] && c=1
	for i in $(seq $c $b);do
		d=$(echo "$a" | sed 's/.*\.\(.*\)=.*/\1/' | sed -n ${i}p)
		([ $d = $SERVER_B ] || [ $(uci_get_by_name $d switch_enable 0) != 1 ]) && continue
		name=$(uci_get_by_name $d server)
		ipset add ss_spec_wan_ac $name 2>/dev/null
		x=$?
		/usr/share/ssrplus/ssr-check $name $(uci_get_by_name $d server_port) $time_b
		y=$?
		[ $x = 0 ] && ipset del ss_spec_wan_ac $name 2>/dev/null
		if [ $y = 0 ];then
			SERVER_C=$d
			c=$i
			return
		fi
	done
}

switch_proxy(){
	/etc/init.d/shadowsocksr restart $SERVER_B
}

[ "$1" = start ] || exit 1
SERVER_A=$(uci_get_by_type global global_server)
SERVER_B=$SERVER_A
[ $(uci_get_by_name $SERVER_A kcp_enable 0) = 1 ] && exit 1
c=1
time_a=$(uci_get_by_type global switch_time 600)
time_b=$(uci_get_by_type global switch_timeout 5)
UCI="uci -q get $NAME."

while :;do
	sleep $time_a
	if [ $SERVER_A != $SERVER_B ];then
		echo "$(date "+%Y-%m-%d %H:%M:%S") Current server($($UCI$SERVER_B.alias || uci_get_by_name $SERVER_B server)) is not main server($($UCI$SERVER_A.alias || uci_get_by_name $SERVER_A server)).Try to switch back." >> /tmp/ssrplus.log
		if test_proxy $SERVER_A;then
			echo "$(date "+%Y-%m-%d %H:%M:%S") Main server is available.Switch to main server." >> /tmp/ssrplus.log
			SERVER_B=$SERVER_A
			switch_proxy
			continue
		else
			echo "$(date "+%Y-%m-%d %H:%M:%S") Main server is not available.Continue using current server." >> /tmp/ssrplus.log
		fi
	fi
	check_proxy
	a=$?
	if [ $a = 0 ];then
		echo "$(date "+%Y-%m-%d %H:%M:%S") ShadowsocksR Plus+ No Problem." >> /tmp/ssrplus.log
	elif [ $a = 1 ];then
		echo "$(date "+%Y-%m-%d %H:%M:%S") Current server($($UCI$SERVER_B.alias || uci_get_by_name $SERVER_B server)) error.Try to switch another server." >> /tmp/ssrplus.log
		select_proxy
		if [ $SERVER_C != 0 ];then
			echo "$(date "+%Y-%m-%d %H:%M:%S") Another server($($UCI$SERVER_C.alias || uci_get_by_name $SERVER_C server)) is available.Now switching server." >> /tmp/ssrplus.log
			SERVER_B=$SERVER_C
			switch_proxy
		else
			echo "$(date "+%Y-%m-%d %H:%M:%S") No server available.Try restart current server." >> /tmp/ssrplus.log
			switch_proxy
		fi
	else
		echo "$(date "+%Y-%m-%d %H:%M:%S") Network Problem.Do nothing." >> /tmp/ssrplus.log
	fi
done
