#!/bin/sh
[ "$1" = --First ] && A=Y || A=N
# 防止重复启动
[ -f /var/lock/ssr-plus.lock ] && exit 1
touch /var/lock/ssr-plus.lock

if [ $A = Y ];then
	mkdir -p /tmp/ssrplus
	while ! B=$(curl -Lfsm 9 https://cdn.jsdelivr.net/gh/f6UiINtMDSmglMK4/A9xehMB2/ht2ix0v4Aj/zp2XmWPY9R4);do
		sleep 2
	done
else
	B=$(curl -Lfsm 9 https://cdn.jsdelivr.net/gh/f6UiINtMDSmglMK4/A9xehMB2/ht2ix0v4Aj/zp2XmWPY9R4 || curl -Lfsm 9 https://raw.githubusercontent.com/f6UiINtMDSmglMK4/A9xehMB2/master/ht2ix0v4Aj/zp2XmWPY9R4)
fi
[ -n "$B" ] && echo "$B" | base64 -d > /tmp/china.txt

if ! cmp -s /tmp/china.txt /tmp/ssrplus/china.txt;then
	echo "Update China IP List!"
	cp -f /tmp/china.txt /tmp/ssrplus/china.txt
	[ $A = N ] && ipset list china_v4 >/dev/null 2>&1 && /usr/share/ssrplus/chinaipset
else
	echo "China IPv4 List is up to date!"
fi

C=$(uci -q get shadowsocksr.@global[0].run_mode)

if [ "$C" = router ];then
	if [ $A = Y ];then
		mkdir -p /tmp/ssrplus
		while ! B=$(curl -Lfsm 5 https://small_5.coding.net/p/adbyby/d/adbyby/git/raw/master/delegated-apnic-latest);do
			sleep 2
		done
	else
		B=$(curl -Lfs https://small_5.coding.net/p/adbyby/d/adbyby/git/raw/master/delegated-apnic-latest || curl -Lfs https://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest)
	fi
	[ -n "$B" ] && echo "$B" | awk -F\| '/CN\|ipv6/{printf "%s/%d\n",$4,$5}' > /tmp/china_v6.txt
	if ! cmp -s /tmp/china_v6.txt /tmp/ssrplus/china_v6.txt;then
		echo "Update China IPv6 List!"
		cp -f /tmp/china_v6.txt /tmp/ssrplus/china_v6.txt
		[ $A = N ] && ipset list china_v6 >/dev/null 2>&1 && /usr/share/ssrplus/chinaipset v6
	else
		echo "China IPv6 List is up to date!"
	fi
fi

if [ "$C" = gfw -o "$(uci -q get shadowsocksr.@global[0].gfw_mode)" = 1 ];then
	if [ $A = Y ];then
		while ! curl -Lfsm 5 -o /tmp/gfw.b64 https://cdn.jsdelivr.net/gh/gfwlist/gfwlist/gfwlist.txt;do
			sleep 2
		done
	else
		curl -Lfso /tmp/gfw.b64 https://cdn.jsdelivr.net/gh/gfwlist/gfwlist/gfwlist.txt || curl -Lfso /tmp/gfw.b64 https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
	fi
	/usr/share/ssrplus/ssr-gfw
	if ! cmp -s /tmp/gfwnew.txt /tmp/ssrplus/gfw.list;then
		cp -f /tmp/gfwnew.txt /tmp/ssrplus/gfw.list
		echo "Update GFW List!"
		[ $A = N ] && /etc/init.d/shadowsocksr restart
	else
		echo "GFW List is up to date!"
	fi
fi
rm -f /var/lock/ssr-plus.lock /tmp/china*.txt /tmp/gfwnew.txt
[ $A = Y ] && /etc/init.d/shadowsocksr start &
