#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@adbyby[-1]
	add ucitrack adbyby
	set ucitrack.@adbyby[-1].init=adbyby
	commit ucitrack
	delete firewall.adbyby
	set firewall.adbyby=include
	set firewall.adbyby.type=script
	set firewall.adbyby.path=/var/etc/adbyby.include
	set firewall.adbyby.reload=1
	commit firewall
EOF

rm -f /tmp/luci-indexcache
killall -HUP rpcd 2>/dev/null
exit 0
