#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@sfe[-1]
	add ucitrack sfe
	set ucitrack.@sfe[-1].init=sfe
	commit ucitrack
EOF

/etc/init.d/sfe enable

rm -f /tmp/luci-indexcache
killall -HUP rpcd 2>/dev/null
exit 0
