#!/bin/sh

if [ $(uci get network.wan.ipv6) == 0 ]; then
	sysctl -w net.ipv6.conf.all.disable_ipv6=1
	sysctl -w net.ipv6.conf.lo.disable_ipv6=1
	sysctl -w net.ipv6.conf.default.disable_ipv6=1
	sysctl -w net.ipv6.conf.all.disable_ipv6=1
else
	sysctl -w net.ipv6.conf.all.disable_ipv6=0
	sysctl -w net.ipv6.conf.lo.disable_ipv6=0
	sysctl -w net.ipv6.conf.default.disable_ipv6=0
	sysctl -w net.ipv6.conf.all.disable_ipv6=0
fi
if [ ! -f /etc/inited ]; then
	[ "$(uci get dhcp.@dnsmasq[0].noresolv)" ] && {
		uci del dhcp.@dnsmasq[0].noresolv
		uci commit dhcp
		service dnsmasq reload
	}
# sh -c "cat '/usr/share/patch/adblock.patch'  | patch -d '/' -p1 --forward" >/dev/null 2>&1
fi

function opkgupgrade() {
	count=0
	while :; do
		curl --connect-timeout 5 https://op.supes.top >/dev/null 2>&1
		if [ "$?" == "0" ]; then
			opkg update
			if [ "$?" == "0" ]; then
			udok=true
			source /etc/profile.d/opkginstall.sh
				if [ ! -f /etc/inited ]; then
					[ -f "/etc/backup/installed_packages.txt" ] && {
						for ipk in $(cat /etc/backup/installed_packages.txt | grep -oE '(.*overlay|luci-app.*|luci-theme.*)' | awk '{print $1}'); do
						 [[ ! $(expr match $ipk 'luci.*opkg.*') ]] && {
							uplog=$(opkg upgrade --force-overwrite --force-checksum $ipk)
							echo $uplog
							[[ ! "$uplog" || "$(echo $uplog|grep 'Configuring')" || "$(echo $uplog|grep 'Not upgrading package')" ]] || {
								udok=false
								rm -f /var/lock/opkg.lock >/dev/null 2>&1
								break
							}
						 }
						done
					}
						[ $udok == true ] && {
							rm /etc/config/*-opkg >/dev/null 2>&1
							touch /etc/inited
						}
				else

					find /usr/lib/opkg/info -name "*.control" \( \
					\( -exec test -f /overlay/upper/{} \; -exec echo {} \; \) -o \
					\( -exec test -f /rom/{} \; -exec find {} -name "luci-app*" \; \) \
					\) | sed -e 's?/usr/lib/opkg/info/\(.*\).control$?\1 overlay?g' >/etc/backup/installed_packages.txt
					[ -f "/etc/backup/installed_packages.txt" ] && {
						opkg list-upgradable >/tmp/list-upgradable
						for ipk in $(cat /etc/backup/installed_packages.txt | grep -oE '(.*overlay|luci-app.*|luci-theme.*)' | awk '{print $1}'); do
							[[ "$(grep $ipk /tmp/list-upgradable)" && ! $(expr match $ipk 'luci.*opkg.*') ]] && {
								uplog=$(opkg upgrade --force-overwrite --force-checksum $ipk)
								echo $uplog
								[[ ! "$uplog" || "$(echo $uplog|grep 'Configuring')" ]] || {
									udok=false
									rm -f /var/lock/opkg.lock >/dev/null 2>&1
									break
								}
							}
						done
					}
						[ $udok == true ] && {
								rm /etc/config/*-opkg >/dev/null 2>&1
						}
				fi
				rm -f /var/lock/opkg.lock >/dev/null 2>&1
				break
			fi
			rm -f /var/lock/opkg.lock >/dev/null 2>&1
		fi
		[ $count -gt 120 ] && break || let count++
		sleep 5
	done
}
opkgupgrade
[[ -f /etc/init.d/adblock && "$(uci get adblock.global.adb_enabled)" == '1' ]] && {
	[ ! -n "$(find /tmp/ -maxdepth 1 -name "adb_list.*")" ] && {
 		/etc/init.d/adblock reload
	}
	[ "$(uci get adblock.global.adb_report)" == '1' ] && {
		/etc/init.d/adblock report >/dev/null 2>&1
	}
}

[[ -f "/bin/coremark" && ! -f "/etc/bench.log" ]] && {
	sleep 5
	/bin/coremark >/tmp/coremark.log
	cat /tmp/coremark.log | grep "CoreMark 1.0" | cut -d "/" -f 1 >/etc/bench.log
	sed -i 's/CoreMark 1.0/(CpuMark/g' /etc/bench.log
	echo " Scores)" >>/etc/bench.log
}) &
