#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@qos_gargoyle[-1]
	add ucitrack qos_gargoyle
	set ucitrack.@qos_gargoyle[-1].init=qos_gargoyle
	commit ucitrack
EOF

rm -rf /tmp/luci-modulecache /tmp/luci-indexcache
killall -HUP rpcd 2>/dev/null
exit 0
