#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Merge-upstream
on:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 */12 * * *
  watch:
    types: started
  repository_dispatch:

jobs:
  merge:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: SSH connection to Actions
      uses: garypang13/debugger-action@master
      if: 1 == 2

    - name: Apply
      run: |
        rm -rf `find -maxdepth 1 -type d -name "[!.]*" ! -path "./diy"`
        git rm -r --cache *
        git clone --depth 1 https://github.com/garypang13/my-packages && mv -f my-packages/* ./ ; rm -Rf my-packages
        git clone --depth 1 https://github.com/garypang13/openwrt-adguardhome AdGuardHome
        git clone --depth 1 https://github.com/garypang13/luci-app-eqos
        git clone --depth 1 https://github.com/garypang13/luci-app-amule
        git clone --depth 1 https://github.com/garypang13/luci-app-xlnetacc
        git clone --depth 1 https://github.com/garypang13/openwrt-filerun && mv -f openwrt-filerun/* ./ ; rm -Rf openwrt-filerun
        git clone --depth 1 https://github.com/garypang13/luci-app-baidupcs-web
        git clone --depth 1 https://github.com/garypang13/luci-theme-edge
        git clone --depth 1 https://github.com/garypang13/autosamba
        git clone --depth 1 https://github.com/garypang13/autocore
        git clone --depth 1 https://github.com/garypang13/luci-app-adblock-plus
        git clone --depth 1 https://github.com/garypang13/openwrt-qbittorrent && mv -f openwrt-qbittorrent/* ./ ; rm -Rf openwrt-qbittorrent
        git clone --depth 1 https://github.com/garypang13/luci-app-homebridge
        git clone --depth 1 https://github.com/garypang13/openwrt-openvpn && mv -f openwrt-openvpn/* ./ ; rm -Rf openwrt-openvpn
        svn co https://github.com/coolsnowwolf/lede/trunk/package/network/services/shellsync
        svn co https://github.com/coolsnowwolf/packages/trunk/net/miniupnpd
        svn co https://github.com/coolsnowwolf/packages/trunk/net/mwan3

        git clone --depth 1 https://github.com/jerrykuku/luci-theme-argon
        git clone --depth 1 https://github.com/jerrykuku/luci-app-vssr
        git clone --depth 1 https://github.com/jefferymvp/luci-app-koolproxyR
        git clone --depth 1 https://github.com/peter-tank/luci-app-dnscrypt-proxy2
        git clone --depth 1 https://github.com/brvphoenix/luci-app-wrtbwmon
        git clone --depth 1 https://github.com/brvphoenix/wrtbwmon
        git clone --depth 1 https://github.com/sirpdboy/luci-app-advanced
        git clone --depth 1 https://github.com/jerrykuku/luci-app-jd-dailybonus
        git clone --depth 1 https://github.com/vernesong/OpenClash && mv -f OpenClash/luci-app-openclash ./ ; rm -Rf OpenClash
        git clone --depth 1 https://github.com/NateLol/luci-app-oled
        git clone --depth 1 https://github.com/destan19/OpenAppFilter && mv -n OpenAppFilter/* ./ ; rm -Rf OpenAppFilter
        git clone --depth 1 https://github.com/esirplayground/luci-app-poweroff
        git clone --depth 1 https://github.com/lvqier/luci-app-dnsmasq-ipset
        git clone --depth 1 https://github.com/sirpdboy/luci-app-netdata
        git clone --depth 1 https://github.com/small-5/ddns-scripts-dnspod
        git clone --depth 1 https://github.com/small-5/ddns-scripts-aliyun
        git clone --depth 1 https://github.com/walkingsky/luci-wifidog luci-app-wifidog
        git clone --depth 1 https://github.com/peter-tank/luci-app-autorepeater

        svn co https://github.com/lisaac/luci-app-dockerman/trunk/applications/luci-app-dockerman
        svn co https://github.com/Lienol/openwrt/trunk/package/network/fullconenat && rm -f fullconenat/patches/000-printk.patch
        svn co https://github.com/srchack/custom-packages/trunk/open-vm-tools
        svn co https://github.com/Lienol/openwrt/trunk/package/lean/luci-app-autoreboot
        svn co https://github.com/NoTengoBattery/openwrt-mt7621/trunk/feeds/luci/applications/luci-app-compressed-memory
        svn co https://github.com/NoTengoBattery/openwrt-mt7621/trunk/package/system/compressed-memory
        svn co https://github.com/Tencent-Cloud-Plugins/tencentcloud-openwrt-plugin-ddns/trunk/tencentcloud_ddns
        svn co https://github.com/teasiu/dragino2/trunk/package/teasiu/luci-app-phtunnel
        svn co https://github.com/teasiu/dragino2/trunk/package/teasiu/luci-app-oray
        svn co https://github.com/teasiu/dragino2/trunk/package/teasiu/phtunnel
        
        rm -rf .svn
        echo -e "\q" | svn co https://github.com/project-openwrt/openwrt/branches/master/package/lean ./
        rm -rf .svn
        echo -e "\q" | svn co https://github.com/coolsnowwolf/lede/trunk/package/lean ./
        rm -rf .svn
        git clone --depth 1 https://github.com/xiaorouji/openwrt-passwall && mv -n openwrt-passwall/* ./ ; rm -Rf openwrt-passwall
        echo -e "\q" | svn co https://github.com/project-openwrt/openwrt/branches/master/package/ctcgfw ./
        rm -rf .svn
        svn export --force https://github.com/project-openwrt/openwrt/branches/master/package/ntlf9t && mv -n ntlf9t/* ./ ; rm -rf ntlf9t
        rm -rf .svn
        echo -e "\q" | svn co https://github.com/project-openwrt/openwrt/branches/master/package/zxlhhyccc ./
        rm -rf .svn
        echo -e "\q" | svn co https://github.com/project-openwrt/openwrt/branches/master/package/lienol ./
        rm -rf .svn
        git clone --depth 1 https://github.com/Lienol/openwrt-package && mv -n openwrt-package/* ./ ; rm -rf openwrt-package 
        
        rm -Rf */.git */.svn qt5 openwrt-chinadns-ng openwrt-simple-obfs openwrt-v2ray-plugin openwrt-fullconenat cups cups-bjnp \
        mt-drivers luci-app-docker coremark openwrt-chinadns luci-app-flowoffload luci-app-sfe luci-app-appfilter fcgiwrap \
        ddns-scripts_aliyun ddns-scripts_dnspod
        mv mt/drivers mt/mt-drivers
        cp -Rf mt/* ./ && rm -Rf mt
        sed -i "/minisign:minisign/d" luci-app-dnscrypt-proxy2/Makefile
        rm -f subconverter/patches/010-missing-header.patch
        sed -i 's/..\/..\/luci.mk/$(TOPDIR)\/feeds\/luci\/luci.mk/g' */Makefile
        cp -rf luci-app-mentohust/luasrc/luci/* luci-app-mentohust/luasrc/ && rm -Rf luci-app-mentohust/luasrc/luci
        bash diy/create_acl_for_luci.sh -a
        bash diy/convert_translation.sh -a || true
        find "diy/patches" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d './' -p1 -E --forward --no-backup-if-mismatch"
        bash diy/diy.sh
        rm -f create_acl_for_luci.warn create_acl_for_luci.err
        sed -i '/"nas".*"NAS"/d' */luasrc/controller/*.lua
        sed -i 's/"admin",\( \|\)"nas"/"admin", "services"/g' */luasrc/controller/*.lua
        for ipk in $(ls); do
        [[ -d "$ipk/root/usr/share/rpcd/acl.d" && -d "$ipk/root/etc/uci-defaults" ]] && {
        [ grep -q "killall -HUP rpcd" $ipk/root/etc/uci-defaults/* ] || {
          sed -i '/exit 0/i killall -HUP rpcd 2>\/dev\/null' $ipk/root/etc/uci-defaults/*
          }
        }
        done
        git add .
        git commit -m "update" || true
        git push
